projects:
  Opulence:
    schemaPath: amplify/backend/api/Opulence/build/schema.graphql
    includes:
      - (src/graphql)
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: eu-west-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
